server:
  port: 8123
  servlet:
    context-path: /api
    session:
      #前端cookie 15天过期   匹配 session15天过期。 实现登录15天过期
      cookie:
        max-age: 1296000
spring:
  application:
    name: MemeHub-Backend
  #mysql数据库配置信息
  datasource:
    url: jdbc:mysql://192.168.83.123:3306/memehub?serverTimezone=Asia/Shanghai
    username: root
    password: 23321212
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active: local
  #文件上传大小限制设置为10mb（默认1mb），这里得是servlet得限制，我们代码里面也是配置得10mb
  servlet:
    multipart:
      max-file-size: 10MB
  #配置session存储15天过期   "我们session目前只存储了登录用户的信息"
  session:
    timeout: 1296000

# mybatis-plus配置信息
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: is_delete # 全局逻辑删除字段名
      logic-delete-value: 1 # 逻辑已删除值。可选，默认值为 1
      logic-not-delete-value: 0 # 逻辑未删除值。可选，默认值为 0

#knife4j配置
knife4j:
  enable: true
  openapi:
    title: Memehub-Backend接口文档
    version: 1.0
    group:
      default:
        api-rule: package
        api-rule-resources:
          - com.voracityrat.memehubbackend.controller
